//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.27 at 01:31:22 AM EEST 
//


package ex_02_JAXB.entity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ex_02_JAXB.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PowerTools_QNAME = new QName("", "power_tools");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ex_02_JAXB.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PowerToolsType }
     * 
     */
    public PowerToolsType createPowerToolsType() {
        return new PowerToolsType();
    }

    /**
     * Create an instance of {@link ModelType }
     * 
     */
    public ModelType createModelType() {
        return new ModelType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PowerToolsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "power_tools")
    public JAXBElement<PowerToolsType> createPowerTools(PowerToolsType value) {
        return new JAXBElement<PowerToolsType>(_PowerTools_QNAME, PowerToolsType.class, null, value);
    }

}
